repos:
  - repo: local
    hooks:
    - id: pre-commit
      name: Tests
      entry: python
      language: system
      args: [pre_commit_tests.py]

    - id: pre-push
      name: Tests before push
      entry: python
      language: system
      stages: [push]
      args: [pre-push_tests.py]

    - id: post-commit
      name: Tests before post
      entry: python
      language: system
      satges: [post-commit]
      args: [post_commit_tests.py]

    - id: commit-msg
      name: Tests before commit msg action
      entry: python
      language: system
      stages: [commit-msg]
      args: [commit-message_tests.py]